name: Build and Deploy

on:
  # mainにプルリクエストをすると起動する
  pull_request:
    branches:
      - main
  # mainにpushをすると起動する
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install NPM packages
      run: npm ci
    - name: Prettier
      run: npm run check-format
    - name: Lint
      run: npm run lint
    - name: Build website
      run: npm run build --if-present
    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
